
p = 28151

def is_primitive_element(g):
    # Set of powers generated by g
    powers = set()

    # Calculate powers of g modulo p
    for i in range(1, p):
        power = pow(g, i, p)
        if power in powers:
            # If a power is repeated, g is not a primitive element
            return False
        powers.add(power)

    # If all elements in Fp are generated by g, it is a primitive element
    return len(powers) == p - 1

# Iterate over elements of Fp
for g in range(1, p):
    if is_primitive_element(g):
        # Found the smallest primitive element
        smallest_primitive_element = g
        break

# Print the smallest primitive element (the flag)
print("Smallest primitive element of Fp:", smallest_primitive_element)
